# Generated by Django 5.2.4 on 2025-07-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqi_category', models.CharField(max_length=100)),
                ('pm10', models.FloatField()),
                ('pm2_5', models.FloatField()),
                ('no2', models.FloatField()),
                ('o3', models.FloatField()),
                ('co', models.FloatField()),
                ('so2', models.FloatField()),
                ('nh3', models.FloatField()),
                ('pb', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Air Quality Data',
                'verbose_name_plural': 'Air Quality Data',
            },
        ),
    ]
